enquete/enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('indicaflix/', include('indicaflix.urls')),
    path('admin/', admin.site.urls),
]

enquete/indicaflix/urls.py
from django.urls import path
from . import views

app_name = 'indicaflix'
urlpatterns = [
    path('',
        views.IndicaFlixView.as_view(), name='index'
    ),
    path('<int:pk>',
        views.DetalhamentoView.as_view(), name = 'detalhamento'
    ),
    path('lista-interesses',
        views.InteressesView.as_view(), name='lista-interesses'
    ),
    path('acionar-interesse/<int:pk>',
        views.acionarInteresse, name='acionar-interesse'
    ),
    path('login',
        views.login_view, name='login'
    ),
    path('logout',
        views.logout_view, name='logout'
    ),
    path('remover-interesse/<int:pk>',
        views.removerIndicacaoDoInteresse, name='remover-interesse'
    ),
    ]

enquete/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='raiz'),
    path('enquete',
        views.IndexView.as_view(), name='index'
    ),
    path('enquete/<int:pk>',
        views.DetalhesView.as_view(), name = 'detalhes'
    ),
    path('enquete/<int:pk>/resultado',
        views.ResultadoView.as_view(), name = 'resultado'
    ),
    path('enquete/<int:id_enquete>/votacao',
        views.votacao, name = 'votacao'
        ),
    path('enquete/<int:pk>/comentdetalhes',
        views.ComentarioView.as_view(), name = 'comentdetalhes'
    ),
    ]

enquete/indicaflix/models.py
from django.contrib.auth.models import User
from django.db import models

class Pessoa(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=255)
    senha = models.CharField(max_length=30)
    nome = models.CharField(max_length=200)
    interesse = models.ManyToManyField("Indicacoes", blank=True, symmetrical=False)

class Indicacoes(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.CharField(max_length=500)
    duracao = models.CharField(max_length=200)
    data_publicacao = models.CharField(max_length=50)
    genero = models.CharField(max_length=100)
    autor = models.CharField(max_length=100)
    data_indicacao = models.DateTimeField('Data da indicação')
    tipo = models.CharField(max_length=50, null=False)

enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime

class Pergunta(models.Model):
    texto = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('Data de publicação')
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora
    publicada_recentemente.admin_order_field = 'data_publicacao'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'últimas 24hs?'

class Opcao(models.Model):
    texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto

class Comentario(models.Model):
    nome_do_autor = models.CharField(max_length=200)
    texto = models.CharField(max_length=200)
    data = models.DateTimeField('Data de inserção')
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)

enquete/indicaflix/views.py
from django.shortcuts import render, reverse, redirect
#from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
#from django.contrib.auth.decorators import login_required
from django.views import generic
from django.utils import timezone
from .models import Indicacoes

class IndicaFlixView(generic.ListView):
    model = Indicacoes
    template_name = 'indicaflix/index.html'

    def get_queryset(self):
        return Indicacoes.objects.filter(data_indicacao__lte=timezone.now()).order_by('-data_indicacao')

class DetalhamentoView(generic.DetailView):
    model = Indicacoes
    template_name = 'indicaflix/detalhamento.html'

class InteressesView(generic.ListView):
    model = Indicacoes
    template_name = 'indicaflix/lista-interesses.html'

#class acionarInteresseView(generic.DetailView):
#    model = Indicacoes
#    template_name = 'indicaflix/acionou-interesse.html'

def acionarInteresse(request, pk):
    if request.user.is_authenticated:
        indicacao_interesse = Indicacoes.objects.get(pk=pk)
        request.user.pessoa.interesse.add(indicacao_interesse)
        return render(request, 'indicaflix/acionou-interesse.html', {'indicacao_interesse':indicacao_interesse})
    else:
        messages.info(request, 'É necessário fazer login para concluir essa ação!')
        return redirect(reverse('indicaflix:login'))

def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('indicaflix:index'))
    else:
        if request.method == 'POST':
            usuario = request.POST.get('username')
            senha = request.POST.get('senha')
            tentativa_login = authenticate(request, username=usuario, password=senha)

            if tentativa_login is not None:
                login(request, tentativa_login)
                return redirect(reverse('indicaflix:index'))
            else:
                messages.error(request, 'Usuário não encontrado: tente novamente')

        return render(request, 'indicaflix/login.html', {})

def logout_view(request):
    logout(request)
    return redirect(reverse('indicaflix:index'))

def removerIndicacaoDoInteresse(request, pk):
    indicacao_retirada = Indicacoes.objects.get(pk=pk)
    request.user.pessoa.interesse.remove(indicacao_retirada)
    return render(request, 'indicaflix/removeu-interesse.html', {'indicacao_retirada':indicacao_retirada})

enquete/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Pergunta, Opcao, Comentario

def home(request):
    return render(request, 'main/home.html')

class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'ultimas_perguntas'
    def get_queryset(self):
        return Pergunta.objects.filter(
            data_publicacao__lte=timezone.now()
            ).order_by('-data_publicacao')[:5]

class DetalhesView(generic.DetailView):
    template_name = 'main/detalhes.html'
    model = Pergunta
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now())

class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'main/resultado.html'

def votacao(request, id_enquete):
    pergunta = get_object_or_404(Pergunta, pk=id_enquete)
    try:
       opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'main/detalhes.html', {
            'pergunta': pergunta,
            'error_message': "Selecione uma opção válida"
        })
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
        return HttpResponseRedirect(reverse('main:resultado',
        args=(pergunta.id,)))

class ComentarioView(generic.DetailView):
    model = Comentario
    template_name ='main/comentdetalhes.html'

enquete/indicaflix/templates/indicaflix/acionou-interesse.html
{% load static %}
<html>
<head>
    <title>IndicaFlix</title>
    <link rel="stylesheet" type="text/css" href="{% static 'indicaflix/style.css' %}">
    <link
        rel="stylesheet"
        href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
        integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V"
        crossorigin="anonymous"
    />
</head>
<body>
    <div class="container">
    <h2>Aplicação do Módulo 2 - IndicaFlix</h2>
    {% if user.is_authenticated %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Uhul! <i class="far fa-grin-stars fa-lg"></i></h4>
            <p><b>{{ indicacao_interesse.nome }}</b> está na sua lista de interesses!</p>
        </div>

        <button class="btn btn-primary rounded-pill"><a class="text-decoration-none text-white" href="{% url 'indicaflix:lista-interesses' %}">Lista de interesses</a></button>
        <button class="btn btn-danger rounded-pill"><a class="text-decoration-none text-white" href="{% url 'indicaflix:index' %}">Voltar para lista de indicações</a></button>

    {% endif %}
    </div>
</body>
</html>

enquete/indicaflix/templates/indicaflix/detalhamento.html
{% load static %}
<html>
<head>
    <title>IndicaFlix</title>
    <link rel="stylesheet" type="text/css" href="{% static 'indicaflix/style.css' %}">
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
      integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V"
      crossorigin="anonymous"
    />
</head>
<body>
    <div class="container">
        <h2>Aplicação do Módulo 2 - IndicaFlix</h2>
        <h4>Detalhes sobre {{ indicacoes.nome }}</h4>
        <ul>
            <li><b>Título:</b> {{ indicacoes.nome }}</li>
            <li><b>Tipo:</b> {{ indicacoes.tipo }}</li>
            <li><b>Descrição:</b> {{ indicacoes.descricao }}</li>
            <li><b>Gênero:</b> {{ indicacoes.genero }}</li>
            <li><b>Duração:</b> {{ indicacoes.duracao }}</li>
            <li><b>Lançamento:</b> {{ indicacoes.data_publicacao }}</li>
            <li><b>Autor/Diretor:</b> {{ indicacoes.autor }}</li> <br>
            <b>Indicação feita dia:</b> {{indicacoes.data_indicacao}}
        </ul>

        <a class="btn btn-success rounded-pill" href="{% url 'indicaflix:acionar-interesse' indicacoes.id %}">Adicionar a lista de interesses</a>
        <a class="btn btn-danger rounded-pill" href="{% url 'indicaflix:index' %}">Voltar para lista de indicações</a>
    </div>
</body>
</html>

enquete/indicaflix/templates/indicaflix/index.html
{% load static %}
<html>

<head>
    <title>IndicaFlix</title>
    <link rel="stylesheet" type="text/css" href="{% static 'indicaflix/style.css' %}">
    <link
    rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
    integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V"
    crossorigin="anonymous"
    />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

</head>

<body>
    <div class="container">
        <h2 class="text-center">Aplicação do Módulo 2 - IndicaFlix</h2>
        <div class="offset-md-4">
            <div class="col-auto">
                {% if user.is_authenticated %}
                <h5>Olá, {{user.pessoa.nome}} <a class="text-decoration-none" href="{% url 'indicaflix:logout' %}"><i
                            class="fas fa-sign-out-alt"></i>Sair</a></h5>
                {% else %}
                <a class="btn btn-success rounded-pill" href="{% url 'indicaflix:login' %}">Fazer login</a>
                {% endif %}
                <a class="btn btn-primary rounded-pill" href="{% url 'indicaflix:lista-interesses' %}">Lista de
                    interesses</a>
            </div>
        </div>

        {% if indicacoes_list %}
        <table id="minha-table" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Titulo</th>
                    <th>Tipo</th>
                    <th>Descrição</th>
                    <th>Visualizar</th>
                </tr>
            </thead>
            <tbody>
                {% for indicacoes in indicacoes_list %}
                <tr>
                    <td>{{ indicacoes.nome }}</td>
                    <td>{{ indicacoes.tipo }}</td>
                    <td>{{ indicacoes.descricao | slice:"0:150" }}...</td>
                    <td><a href="{% url 'indicaflix:detalhamento' indicacoes.id %}"><i class="far fa-eye fa-2x"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Titulo</th>
                    <th>Tipo</th>
                    <th>Descrição</th>
                    <th>Visualizar</th>
                </tr>
            </tfoot>
        </table>

        {% else %}
        <h3>Desculpe, ainda não há indicações cadastradas.</h3>
        {% endif %}
    </div>

    <script>
        $(document).ready(function () {
            $('#minha-table').DataTable({
                "language": {
                    "search": "Pesquisar:",
                    "searchPlaceholder": "Nome da indicação...",
                    "lengthMenu": "Mostrando _MENU_ registros por página",
                    "zeroRecords": "Nenhuma indicação encontrada",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Nenhum indicação disponível",
                    "infoFiltered": "(Filtrando de _MAX_ de indicações no total)",
                    "paginate": {
                        "first": "Primeiro",
                        "last": "Ultimo",
                        "next": "Proximo",
                        "previous": "Anterior",
                    },
                }
            });
            $('select').select();
        });
    </script>

</body>

</html>

enquete/indicaflix/templates/indicaflix/lista-interesses.html
{% load static %}
<html>
<head>
    <title>IndicaFlix</title>
    <link rel="stylesheet" type="text/css" href="{% static 'indicaflix/style.css' %}">
    <link
        rel="stylesheet"
        href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
        integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V"
        crossorigin="anonymous"
    />
</head>
<body>
    <div class="container">
        <h2>Aplicação do Módulo 2 - IndicaFlix</h2>
        {% if user.is_authenticated %}

            {% if request.user.pessoa.interesse.count == 0 %}
                <div class="alert alert-warning" role="alert">
                    <h4 class="alert-heading">Ah, não! <i class="far fa-sad-tear fa-lg"></i></h4>
                    <p>Você ainda não tem indicação na sua lista de interesses</p>
                    <hr>
                    <p class="mb-0">Sugerimos que volte as indicações para encontrar algo legal pra você!</p>
                </div>
            {% endif %}

            <ul>
                {% for i in request.user.pessoa.interesse.all %}
                    <li><b>Título:</b> {{ i.nome }}</li>
                    <li><b>Tipo:</b> {{ i.tipo }}</li>
                    <li><a class="btn btn-danger" href="{% url 'indicaflix:remover-interesse' i.id %}"><i class="far fa-trash-alt fa-lg"></a></i></li>
                    <hr>
                {% endfor %}
            </ul>

        {% else %}
        <div class="alert alert-danger" role="alert">
            <p>Você precisa estar logado no sistema para poder ter acesso a sua lista de interesses!</p>
        </div>
        <a class="btn btn-success rounded-pill" href="{% url 'indicaflix:login' %}">Fazer login</a>
        {% endif %}
        <a class="btn btn-primary rounded-pill" href="{% url 'indicaflix:index' %}">Ver mais indicações</a>
    </div>
</body>
</html>

enquete/indicaflix/templates/indicaflix/login.html
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'indicaflix/style.css' %}">
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
      integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V"
      crossorigin="anonymous"
    />
    <title>IndicaFlix</title>
</head>

<body>

    <div class="container">
        <h2 class="text-center">Aplicação do Módulo 2 - IndicaFlix</h2>

        {% if messages %}
        <div class="alert alert-danger" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        <form action="" id="create-class" method="POST">
            {% csrf_token %}
            <h3 class="text-center"><i class="fas fa-lock"></i>Login</h3>
            <div class="form-group">
                <div class="col-md-6 offset-md-3">
                    <label for="username">E-mail:</label>
                    <input class="form-control" name="username" placeholder="Digite seu e-mail" id="name" required>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6 offset-md-3">
                    <label for="senha">Senha:</label>
                    <input class="form-control" name="senha" placeholder="Digite sua senha" id="avatar" type="password" required>
                </div>
            </div>
            <br>
            <div class="col-md-6 offset-md-3">
                <input type="submit" class="btn btn-success rounded-pill" value="login">
                <a class="btn btn-danger rounded-pill" href="{% url 'indicaflix:index' %}">Voltar para lista de indicações</a>
            </div>
        </form>
    </div>
</body>

</html>

enquete/indicaflix/templates/indicaflix/removeu-interesse.html
{% load static %}
<html>
<head>
    <title>IndicaFlix</title>
    <link rel="stylesheet" type="text/css" href="{% static 'indicaflix/style.css' %}">
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
      integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V"
      crossorigin="anonymous"
    />
</head>
<body>
    <div class="container">
        <h2>Aplicação do Módulo 2 - IndicaFlix</h2>
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Feito! <i class="far fa-laugh-wink fa-lg"></i></h4>
            <p>Você removeu <b>{{ indicacao_retirada.nome }}</b> da sua lista de interesses!</p>
            <hr>
            <p class="mb-0">Esperamos que tenha desfrutado bastante da indicação</p>
        </div>

        <a class="btn btn-primary rounded-pill" href="{% url 'indicaflix:lista-interesses' %}">Ver minha lista de interesses</a>
        <a class="btn btn-secondary rounded-pill" href="{% url 'indicaflix:index' %}">Voltar para lista de indicações</a>
    </div>
</body>
</html>

enquete/main/templates/main/comentdetalhes.html
<html>
    <head>
        <title>Enquete</title>
    </head>
    <body>
        <h2>** Detalhes do comentário **</h2>
        <ul>
            <u>Nome do autor</u>: {{ comentario.nome_do_autor }} <br>
            <u>Data de inserção</u>: {{ comentario.data }}
        </ul>
        <a href="{%url 'main:detalhes' comentario.pergunta.id %}">Voltar para a enquete</a> |
        <a href="{%url 'main:index'%}"> Retornar para a home</a>
    </body>
</html>

enquete/main/templates/main/detalhes.html
<html>
    <head>
        <title>Enquete</title>
    </head>
    <body>
        <h2>** Detalhes da enquete {{ pergunta.id }} **</h2>
        <u>Pergunta</u>: {{ pergunta.texto }}<br/>
        <u>Data de publicação</u>: {{ pergunta.data_publicacao}}
        {% if error_message %}
            <hr>
                <strong> {{ error_message }} </strong>
            </hr>
        {% endif %}
        <form action="{% url 'main:votacao' pergunta.id %}" method="post">
            {% csrf_token %}
            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                    <li><input type="radio" name="opcao"
                        id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
                        <label for="opcao{{ forloop.counter }}">
                            {{ opcao.texto }}
                        </label>
                    </li>
                {% endfor %}
            </ul>
                <input type="submit" value="Votar">
        </form>
        <ul>
            <u>Comentarios</u>:
            {% for comentario in pergunta.comentario_set.all %}
                    <li><a href="{% url 'main:comentdetalhes' comentario.id %}">
                    {{ comentario.texto }}</a></li>
            {% endfor %}
        </ul>
    </body>
</html>

enquete/main/templates/main/home.html
<html>
    <head>
        <title>Aplicações DSWeb 2020.1</title>
    </head>
    <body>
        <h2>Aplicações da Disciplina de Dev. Web 2020.1</h2>
        <h4>Selecione a aplicação desejada:</h4>
        <ul>
            <li><a href="{% url 'main:index' %}">Aplicação Enquete - Módulo 1</a></li>
            <li><a href="{% url 'indicaflix:index' %}">Aplicação IndicaFlix - Módulo 2</a></li>
        </ul>
        <hr>
        <b>Ana Paula Oliveira</b> (<i>oliveira.a@academico.ifrn.edu.br</i>)
    </body>
</html>

enquete/main/templates/main/index.html
{% load static %}
<html>
    <head>
        <title>Enquete</title>
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    </head>
    <body>
        {% if ultimas_perguntas %}
            <h2>** Lista das últimas enquetes **</h2>
            <ul>
                {% for pergunta in ultimas_perguntas %}
                    <li><a href="{% url 'main:detalhes' pergunta.id %}">
                    {{ pergunta.texto }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>Não há enquetes cadastradas até o momento! :( </h3>
        {% endif %}
    </body>
</html>

enquete/main/templates/main/resultado.html
<html>
    <head>
        <title>Enquete</title>
    </head>
    <body>
        <h2>** Resultado parcial da enquete {{pergunta.id}} **</h2>
        <u>Pergunta</u>: {{ pergunta.texto }}<br/>
        <u>Data de publicação</u>: {{ pergunta.data_publicacao}}
        <ul>
            {% for opcao in pergunta.opcao_set.all %}
                <li> {{ opcao.texto }} = {{ opcao.votos}}
                voto{{ opcao.votos | pluralize }}</li>
            {% endfor %}
        </ul>
        <hr/>
        <a href="{% url 'main:detalhes' pergunta.id %}">Votar novamente</a> |
        <a href="{%url 'main:index'%}"> Retornar para a home</a>
    </body>
</html>